# Generated by Django 5.2.3 on 2025-06-30 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date(2025, 6, 29), verbose_name='Attendance record date'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 -- Poor'), (2, '2'), (3, '3'), (4, '4'), (5, '5 -- Above expectation')], default=5),
        ),
        migrations.AlterField(
            model_name='performance',
            name='review_date',
            field=models.DateField(default=datetime.date(2025, 6, 29), verbose_name='Performance review date'),
        ),
    ]
