# Generated by Django 5.2.3 on 2025-06-30 19:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_alter_attendance_date_alter_performance_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Attendance record date'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='review_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Performance review date'),
        ),
    ]
