# Generated by Django 5.2.3 on 2025-07-01 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_alter_attendance_date_alter_performance_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, help_text='1=Poor, 5=Above expectation'),
        ),
    ]
