# Generated by Django 5.2.3 on 2025-07-01 09:10

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0006_alter_performance_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2025, 7, 1), message='Date cannot be in the future')], verbose_name='Attendance record date'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, help_text='1 = Poor, 5 = Excellent'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='review_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2025, 7, 1), message='Date cannot be in the future')], verbose_name='Performance review date'),
        ),
    ]
