# Generated by Django 5.2.3 on 2025-07-02 02:44

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0007_alter_attendance_date_alter_performance_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2025, 7, 2), message='Date cannot be in the future')], verbose_name='Attendance record date'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='review_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2025, 7, 2), message='Date cannot be in the future')], verbose_name='Performance review date'),
        ),
    ]
