# Generated by Django 5.2.3 on 2025-06-30 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(default=datetime.date(2025, 6, 29), verbose_name='Date of joining'),
        ),
    ]
