# Generated by Django 5.2.3 on 2025-06-30 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_date_of_joining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(default=datetime.date(2025, 6, 30), verbose_name='Date of joining'),
        ),
    ]
