# Generated by Django 5.2.3 on 2025-06-30 19:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_date_of_joining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of joining'),
        ),
    ]
