# Generated by Django 5.2.3 on 2025-07-01 02:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_remove_employee_date_of_joining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(help_text='Format: (123) 456-7890', max_length=14, validators=[django.core.validators.RegexValidator('^\\(\\d{3}\\) \\d{3}-\\d{4}$', message='Phone number must be in the format (123) 456-7890')]),
        ),
    ]
